### hello API
GET localhost:8080/api/hello

### 게시글 생성 API
POST localhost:8080/api/board
Content-Type: application/json

{
  "title": "게시글 제목",
  "content": "게시글 내용"
}

### 게시글 조회 API
GET localhost:8080/api/board/2


